openapi: 3.1.0
info:
  title: Rescue Common API
  description: Общие типы и контрактные компоненты сервисов Rescue.
  version: 0.0.1
paths: {}
components:
  schemas:
    Gender:
      type: string
      description: Пол человека
      enum:
        - MALE
        - FEMALE
    Latitude:
      type: number
      format: double
      minimum: -90
      maximum: 90
      description: Географическая широта
    Longitude:
      type: number
      format: double
      minimum: -180
      maximum: 180
      description: Географическая долгота
    GeoPoint:
      type: object
      description: Географическая точка
      required:
        - lat
        - lon
      properties:
        lat:
          $ref: '#/components/schemas/Latitude'
        lon:
          $ref: '#/components/schemas/Longitude'
    IncidentId:
      type: string
      format: uuid
      description: Идентификатор инцидента
    SettlementInfo:
      type: object
      description: Населённый пункт и его район
      properties:
        settlementName:
          type: string
          description: Название населённого пункта
          maxLength: 255
        settlementDistrictName:
          type: string
          description: Название района населённого пункта
          maxLength: 255
