<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ru.rom8.rescue</groupId>
    <artifactId>rescue-api-contracts</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Rescue API contracts</name>
    <description>OpenAPI-контракты сервисов Rescue</description>

    <modules>
        <module>common-api-contract</module>
        <module>volunteer-api-contract</module>
        <module>incident-api-contract</module>
        <module>tracking-api-contract</module>
    </modules>

    <properties>
        <maven.compiler.release>25</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven-dependency-plugin.version>3.10.0</maven-dependency-plugin.version>
    </properties>

    <dependencies>

    </dependencies>

</project>
